### ISSUE TITLE
The inability to override default classes

### ISSUE THREAD

**Issue by cheyner** [glhd/aire#1]
The way default classes work makes it difficult to customize styling for elements.  In our example template, there is a bottom margin on form groups (mb-6).  Trying to override that bottom margin via something like...
`{!! Aire::submit("I'm unavailable")->groupClass('mb-0') !!}`
..does not work, as the `mb-6` class takes precedence.

**Comment by cheyner** [comment]
Some thoughts about this issue...
We may be able to workaround this behavior with some strategy for how we setup these default styles.  Rather than using tailwind (which is hard to override due to its !important declarations), we may want to use more traditional CSS classes for our core elements.  Those would be easier to override with adhoc tailwind classes when an element is rendered.

**Comment by inxilpro** [comment]
I think we can address this in two ways. The first is to move more of the classes into config rather than having them hard coded into the components. I always planned on doing that, and just figured that would be a refactor near the end—once I was happy with the look and feel. The other is to allow for two layers of styles—the core styles and the aesthetic styles—and make it easy to override the latter without messing with the former. Still thinking that one thru, but I have some ideas. Are there particular use cases that you can think of that you’re trying to address?

**Comment by cheyner** [comment]
That seems like a fine plan.  I'd say customizing margins around an element is the main use case I have in mind.

**Comment by cheyner** [comment]
Though I will say that I think this could be solved with changes to our implementation of templates, rather than adding style layers (which would make for greater complexity in the code).  Despite loving tailwind on the frontend, it seems uniquely ill-suited as a baseline for customization.
