### ISSUE TITLE
php 8.x behaves different than 7.4 with your Attributes::isValue function

### ISSUE THREAD

**Issue by Jossnaz** [glhd/aire#74]
I want to use

Aire::radioGroup

and I want it to be _emtpy_ on render. NO VALUE selected. And values are 0,1,2
so in my local dev I set the value to '' thus no value gets selected under PHP 8

then I deploy to server, doesnt work because my server runs 7.4

https://kinsta.com/blog/php-8/#string-to-number-comparison

btw:

how do you render radio group in 7.4 without selecting a value?

**Comment by inxilpro** [comment]
Because of the fact that all form inputs are technically strings, we had to make a decision about how to treat `null`, `false`, and `0` in comparison. Unfortunately, there's no solution that just works in call cases.

Here, the easiest option is to just do something like:

```php
Aire::radioGroup([0, 1, 2], 'foo')->defaultValue(PHP_INT_MIN);
```

This will ensure that none of your values are considered equal and checked by default.
